apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: my-csi-cr
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - events
  verbs:
  - patch
  - create
  - list
  - watch
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  - volumeattachments/status
  - storageclasses
  - csinodes
  verbs:
  - list
  - patch
  - watch
